config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#index'

  get 'samirrr', to: 'pages#samirrr', as: 'samirrr'

  get 'prestongrant', to: 'pages#prestongrant', as: 'prestongrant'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def samirrr
  end

  def prestongrant
    render :prestongrant
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamCollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Directory of Student Pages</h1>

<ul>
    <li><%= link_to 'samirrr', samirrr_path %></li>

    <li><%= link_to 'prestongrant', prestongrant_path %></li>
</ul>

app/views/pages/prestongrant.html.erb
<h1>About Me</h1>

<ul>
    <li>I am a Junior at U of M</li>
    <li>I am majoring in Computer Science</li>
    <li>This is my first year at U of M</li>
</ul>

app/views/pages/samirrr.html.erb
<!DOCTYPE html>
<html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <title>About</title>
    <style>
        body{
    background-color:#363945;
    color: #c6c8d2;}
    </style>
</head>

<body>
<%= yield %>
<div class="container-fluid" style="margin-top: 40px; margin-left: 100px; width: 80%;">
      <h1 class="title">Samir's A Little More About Me</h1>
    <br>
    <p>I am currently a student in the University of Memphis. It has always been my passion ever since a kid to learn 
        and apply tech. One aspect of tech that I would like to focus on is the Cloud. I am really intrigued about how 
        it works and the architecture behind it. I was able to understand the basics of the cloud when I obtained my 
        Amazon Web Services Certified Cloud Practitioner certification. If anyone knows how I can grow my skills or 
        has questions related to starting off learning about the cloud please let me know.</p>
    
  </div>

  
    


</body>


</html>